
pointcloud_to_laserscan:
  ros__parameters:
    use_sim_time: true
    target_frame: velodyne
    transform_tolerance: 0.01
    min_height: -0.30  # origin is the sensor
    max_height: 1.4  # origin is the sensor
    angle_min: -2.57  # -M_PI/2 - 1.0 (angle clipping)
    angle_max: 1.57  # M_PI/2
    angle_increment: 0.00436  # M_PI/360/2
    scan_time: 0.1
    range_min: 0.2
    range_max: 50.0
    use_inf: true
    inf_epsilon: 1.0
    # Concurrency level affects number of pointclouds queued for
    # processing and number of threads used
    # 0 : Detect number of cores
    # 1 : Single threaded
    # 2->inf : Parallelism level
    concurrency_level: 0                

filter_crop_box_node:
  ros__parameters:
    use_sim_time: true
    min_x: -0.7
    min_y: -0.6
    min_z: 0.0
    max_x: 0.2
    max_y: 0.1
    max_z: 2.0
    keep_organized: false
    negative: true
    input_frame: "base_link"
    output_frame: "velodyne"
