# Copyright (c) 2020  Carnegie Mellon University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: local/odom
    robot_base_frame: local/base_footprint
    odom_topic: /local/odom
    enable_groot_monitoring: False
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - cabot_people_exist_bt_node
    - cabot_someone_on_path_bt_node
    - cabot_someone_not_in_queue_bt_node
    - cabot_far_enough_bt_node
    - cabot_need_to_avoid_bt_node
    - cabot_need_to_replan_bt_node
    - cabot_check_path_bt_node
    - cabot_can_pass_person_bt_node
    - cabot_ignore_people_bt_node
    - cabot_person_stops_bt_node
    - cabot_change_param_bt_node
    - cabot_restore_config_bt_node
    - cabot_wait_float_bt_node
    - cabot_publish_topic_bt_node


bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True


controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 5.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "cabot_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    # It is not going to use progress_checker as of 2020/08/27.
    # It may need to identify this so that it can tell the user about the problem
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.0 # disable checker (loalization's fractuation may enough
      movement_time_allowance: 10000000.0 # just for sure
    # Goal checker parameters
    cabot_goal_checker:
      plugin: "cabot_navigation2::CabotSimpleGoalChecker"
      xy_goal_tolerance: 0.50
      yaw_goal_tolerance: 6.28
      stateful: True
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      trajectory_generator_name: "dwb_plugins::LimitedAccelGenerator" # default: dwb_plugins::StandardTrajectoryGenerator
      debug_trajectory_details: True
    #  prune_plan: True # default: True
      prune_distance: 1.0 # default: 1.7 # should be greater than max_vel_x * sim_time + some margin
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.5
      max_vel_y: 0.0
      max_vel_theta: 2.0
      min_speed_xy: 0.0
      max_speed_xy: 1.0
      min_speed_theta: 0.0
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 0.8
      acc_lim_y: 0.0
      acc_lim_theta: 1.0 # default 2.0
      decel_lim_x: -0.5
      decel_lim_y: 0.0
      decel_lim_theta: -1.0 # default -2.0
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7 #  default 1.7
    #  discretize_by_time: False # default = False
    #  time_granularity: 0.1 # default = 0.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.5
      critics: ["Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.008 # default: 1.0
      BaseObstacle.sum_scores: False # default: False
      PathAlign.scale: 32.0
      GoalAlign.scale: 4.0
      GoalAlign.forward_point_distance: 0.35
      PathDist.scale: 32.0
      GoalDist.scale: 4.0
      RotateToGoal.scale: 32.0
      short_circuit_trajectory_evaluation: True
      trans_stopped_velocity: 0.25
      slowing_factor: 5.0
      lookahead_time: -1.0
      stateful: True

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: local/odom
      robot_base_frame: local/base_footprint
      use_sim_time: True
      rolling_window: True
      width: 10
      height: 10
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      robot_radius: 0.45
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # robot_radius + safe_margin
        inflation_radius: 0.45
        cost_scaling_factor: 3.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /local/scan
          min_obstacle_height: -100.0
          max_obstacle_height: 100.0
          obstacle_range: 4.0
          raytrace_range: 5.0
          clearing: True
          marking: True
          inf_is_valid: True # default: False
          data_type: "LaserScan"
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      robot_base_frame: local/base_footprint
      global_frame: local/odom
      rolling_window: True
      width: 20
      height: 20
      use_sim_time: True
      plugins: ["obstacle_layer", "inflation_layer"]
      robot_radius: 0.45
      resolution: 0.05
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        # robot_radius + safe_margin
        inflation_radius: 0.35
        cost_scaling_factor: 5.0
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /local/scan
          min_obstacle_height: -100.0
          max_obstacle_height: 100.0
          obstacle_range: 8.0
          raytrace_range: 8.0
          clearing: True
          marking: True
          inf_is_valid: True # default: False
          data_type: "LaserScan"
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 2.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True


recoveries_server:
  ros__parameters:
    costmap_topic: /local/local_costmap/costmap_raw
    footprint_topic: /local/local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: local/odom
    robot_base_frame: local/base_footprint
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.5
    min_rotational_vel: 0.01
    rotational_acc_lim: 0.2
