# config file for cabot2-gt1

# include/vlp16.launch.py
pointcloud_to_laserscan_node:
  ros__parameters:
    angle_min: -2.57  # -M_PI/2 - 1.0 (angle clipping)
    angle_max: 1.57  # M_PI/2

cabot:
  cabot_handle_v2_node:
    ros__parameters:
      buttons: 
        - BUTTON_UP
        - BUTTON_DOWN
        - BUTTON_LEFT
        - BUTTON_RIGHT


  cabot_serial:
    ros__parameters:
      port: /dev/ttyARDUINO_MEGA


  odriver_adapter_node:
    ros__parameters:
      bias: 0.21
      gain_omega: 1.0
      gain_omega_i: 0.0

  odriver_node:
    ros__parameters:
      wheel_diameter: 0.073
      count_per_round: 8192
      left_is_1: false
      is_clockwise: true
      gain_left: 1.0
      gain_right: 1.0
      vel_gain: 1.0
      vel_integrator_gain: 10.0
      motor_bandwidth: 200
      encoder_bandwidth: 200
