buttons:
  -
    value: BUTTON_UP
    name: Up
  -
    value: BUTTON_DOWN
    name: Down
  -
    value: BUTTON_LEFT
    name: Left
  -
    value: BUTTON_RIGHT
    name: Right
  -
    value: BUTTON_CENTER
    name: Center
