# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

# services is defined in docker-compose-common.yaml

services:
  ros1:
    extends:
      file: docker-compose-common.yaml
      service: ros1
    environment:
      - CABOT_GAZEBO=0
      - CABOT_TOUCH_ENABLED=1

  bridge:
    extends:
      file: docker-compose-common.yaml
      service: bridge

  ros2:
    extends:
      file: docker-compose-common.yaml
      service: ros2
    command:
      - "/launch.sh"
      - "-T ${CABOT_SITE:-cabot_site_cmu_3d}"  # cabot site
      - "-x ${CABOT_INITX:-0}"              # initial X
      - "-y ${CABOT_INITY:-0}"              # initial Y
      - "-Z ${CABOT_INITZ:-0}"              # initial Z
      - "-a ${CABOT_INITA:-0}"              # initial rotation
      - "-M"                                # use multifloor localization (no amcl)
      - "-o"                                # do not show local rviz2
      # "-O"                                # do no show rviz2
      - "-c"                                # use built cache                             

  localization:
    extends:
      file: docker-compose-common.yaml
      service: localization
    command: ["/launch.sh",
              "localization",
              #"-s",                                # gazebo
              "-T ${CABOT_SITE:-cabot_site_cmu_3d}", # cabot site
              "-r ${ROBOT:-cabot2-gt1}",           # robot type
              "-M",                                # start multifloor map server
              "-R 1",                              # set publish_current_rate to 1hz
              "-p",                                # use pressure topic
              #"-C",                                # launch cvi client
              ]

  people:
    extends:
      file: docker-compose-common.yaml
      service: people
    command: ["/launch.sh",
              #"-s",                                # gazebo
              "-W",                                # wait roscore
              "-T ${CABOT_SITE:-cabot_site_cmu_3d}", # cabot site
              "-r",                                # realsense physicial (-s or -r)
              "-q",                                # queue
              #"-p",                                # people topic is simulation groundtruth
              "-C",                                # check required before launch
              "-D",                                # detection
              "-K",                                # tracking
              #"-V",                                # show rviz
              ]

  ble_scan:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan
