# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

# configuration of real robot for 3 Realsense on a PC configuration
# services extend from docker-compose-rs3.yaml

services:
  ros1:
    extends:
      file: docker-compose-rs3.yaml
      service: ros1
    environment:
      - CABOT_GAZEBO=0
      - CABOT_TOUCH_ENABLED=1

  bridge:
    extends:
      file: docker-compose-rs3.yaml
      service: bridge

  ros2:
    extends:
      file: docker-compose-rs3.yaml
      service: ros2
    environment:
      - CABOT_GAZEBO=0

  localization:
    extends:
      file: docker-compose-rs3.yaml
      service: localization
    environment:
      - CABOT_GAZEBO=0
      - CABOT_PRESSURE_AVAILABLE=1

# people service only queue and tracking
  people-nuc:
    extends:
      file: docker-compose-rs3.yaml
      service: people-nuc
    environment:
      - CABOT_GAZEBO=0

  people-rs1:
    extends:
      file: docker-compose-rs3.yaml
      service: people-rs1
    environment:
      - CABOT_GAZEBO=0

  people-rs2:
    extends:
      file: docker-compose-rs3.yaml
      service: people-rs2
    environment:
      - CABOT_GAZEBO=0

  people-rs3:
    extends:
      file: docker-compose-rs3.yaml
      service: people-rs3
    environment:
      - CABOT_GAZEBO=0

  ble_scan:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan

