# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
version: "2.3"

# configuration of real robot for single PC
# services environments are overrideed

services:
  navigation:
    extends:
      file: docker-compose.yaml
      service: navigation
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0
      - CABOT_TOUCH_ENABLED=${CABOT_TOUCH_ENABLED:-true}

  gui:
    extends:
      file: docker-compose-common.yaml
      service: gui
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0

  driver:
    extends:
      file: docker-compose-common.yaml
      service: driver

  localization:
    extends:
      file: docker-compose.yaml
      service: localization
    environment:
      - CABOT_GAZEBO=0
      - CABOT_PRESSURE_AVAILABLE=0

  people:
    extends:
      file: docker-compose.yaml
      service: people
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1

#  wifi_scan:
#    extends:
#      file: docker-compose-common.yaml
#      service: wifi_scan

  ble_scan:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan

  mosquitto:
    extends:
      file: cabot-mqtt/docker-compose.yaml
      service : mosquitto
    environment:
      - CYCLONEDDS_URI=/home/developer/cyclonedds.xml

  mqtt_client:
    extends:
      file: cabot-mqtt/docker-compose.yaml
      service : mqtt_client
      
    environment:
      - CYCLONEDDS_URI=/home/developer/cyclonedds.xml
    volumes:
      - ./cabot-mqtt/docker/ros2_ws/install/cabot_mqtt:/opt/custom_ws/install/cabot_mqtt
      - ./cabot-mqtt/docker/ros2_ws/install/mqtt_ros:/opt/custom_ws/install/mqtt_ros
      - ./cabot-mqtt/docker/ros2_ws/install/mqtt_msgs:/opt/custom_ws/install/mqtt_msgs
      - ./cabot-mqtt/docker/ros2_ws/install/ios_msgs:/opt/custom_ws/install/ios_msgs

    command:
      - "/launch.sh"
      - "-c"

  uwb_tag_publisher_1:
    extends: 
      file : cabot-phone-alignment/docker-compose.yaml
      service : develop
    volumes:
      - /dev:/dev
    command: > 
      /bin/bash -c '
          /ros_entrypoint.sh && 
          source ros2_ws/install/local_setup.bash && 
          ros2 run uwbtag_publisher uwbtag_publisher \
            --ros-args -p topic_name:=uwb_tag \
            --ros-args -p serial_port:="/dev/ttyUWB0" \
            --ros-args -p frame_id:="uwb_tag1_link" \
            --ros-args --log-level FATAL
      '
      
    stop_signal: SIGINT

  uwb_tag_publisher_2:
    extends: 
      file : cabot-phone-alignment/docker-compose.yaml
      service : develop
    volumes:
      - /dev:/dev
    command: > 
      /bin/bash -c '
          /ros_entrypoint.sh && 
          source ros2_ws/install/local_setup.bash && 
          ros2 run uwbtag_publisher uwbtag_publisher \
            --ros-args -p topic_name:=uwb_tag \
            --ros-args -p serial_port:="/dev/ttyUWB1" \
            --ros-args -p frame_id:="uwb_tag2_link" \
            --ros-args --log-level FATAL
      '
    stop_signal: SIGINT

  uwb_tag_publisher_3:
    extends: 
      file : cabot-phone-alignment/docker-compose.yaml
      service : develop
    volumes:
      - /dev:/dev
    command: > 
      /bin/bash -c '
          /ros_entrypoint.sh && 
          source ros2_ws/install/local_setup.bash && 
          ros2 run uwbtag_publisher uwbtag_publisher \
            --ros-args -p topic_name:=uwb_tag \
            --ros-args -p serial_port:="/dev/ttyUWB2" \
            --ros-args -p frame_id:="uwb_tag3_link" \
            --ros-args --log-level FATAL
      '
    stop_signal: SIGINT
  # debug:
  #   extends:
  #     file: docker-compose-common.yaml
  #     service: ros2
  #   environment:
  #     - CABOT_GAZEBO=1
  #     - CABOT_USE_SIM_TIME=1
  #   command: ["bash"]
    
