# Copyright (c) 2023  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

# configuration of simulation for single PC
# services extend from docker-compose-common.yaml

services:
  ros1:
    extends:
      file: docker-compose-common.yaml
      service: ros1
    command:
      - "launch.sh"
      # - "-d"                                # debug
      - "-u"                                # UI manager
      - "-r"                                # remote control
      - "-E"                                # explore mode
      - "-c"                                # use built cache

  bridge:
    extends:
      file: docker-compose-common.yaml
      service: bridge
    command:
      - '/launch.sh'
      - "-e"                                # explore mode
      - "-c"                                # use built cache

  ros2:
    extends:
      file: docker-compose-common.yaml
      service: ros2
    command:
      - "/launch.sh"
      - "-M"                  # do not use amcl
      - "-e"                  # explore mode
      - "-c"                  # use built cache

  explore:
    build:
      context: ./docker/explore
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_IP
      - ROS_MASTER_URI=http://${MASTER_IP:-127.0.0.1}:11311
      - ROS_LOG_DIR
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./docker/home:/home/developer
      - ./cabot:/home/developer/explore_ws/src/cabot
      - ./cabot_description:/home/developer/explore_ws/src/cabot_description
      - ./cabot_msgs:/home/developer/explore_ws/src/cabot_msgs
      - ./cabot_ui:/home/developer/explore_ws/src/cabot_ui
      - ./cabot_explore:/home/developer/explore_ws/src/cabot_explore
      - ./cabot_explore_msgs:/home/developer/explore_ws/src/cabot_explore_msgs
      - ./motor_controller:/home/developer/explore_ws/src/motor_controller
      - ./route_explore:/home/developer/explore_ws/src/route_explore
      - ./route_explore_msgs:/home/developer/explore_ws/src/route_explore_msgs
      - ./route_explore_rviz:/home/developer/explore_ws/src/route_explore_rviz
      - ./docker/bridge/ros1/nav2_msgs:/home/developer/explore_ws/src/nav2_msgs
      - ./docker/bridge/ros1/people/people_msgs:/home/developer/explore_ws/src/people_msgs
      - ./docker/bridge/ros1/queue_msgs:/home/developer/explore_ws/src/queue_msgs
      - ./docker/home/catkin_ws/src/velodyne_simulator/velodyne_description:/home/developer/explore_ws/src/velodyne_description
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    tty: true
    stdin_open: true
    command:
      - "/launch.sh"
      # - "-b explore.bag"    # for explore_evaluation.launch
      - "-s"                  # gazebo

  people:
    extends:
      file: docker-compose-common.yaml
      service: people