# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

services:
  navigation:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: navigation-base
    volumes:
      - ./docker/home:/home/developer/

  gazebo:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: gazebo-base
    volumes:
      - ./docker/home:/home/developer/

  gui:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: gui-base
    volumes:
      - ./docker/home:/home/developer/

  localization:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: localization-base
    volumes:
      - ./docker/home:/home/developer/

  people-base:
    build:
      context: ./docker/people
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_IP=${ROS_IP:-127.0.0.1}
      - GAZEBO_IP=${ROS_IP:-127.0.0.1}
      - ROS_MASTER_URI=http://${MASTER_IP:-127.0.0.1}:11311
      - GAZEBO_MASTER_URI=http://${MASTER_IP:-127.0.0.1}:11345
      - OMP_NUM_THREADS=1
      - ROS_LOG_DIR
# CaBot
      - CABOT_GAZEBO=${CABOT_GAZEBO:-1}
      - CABOT_SITE
      - CABOT_SHOW_PEOPLE_RVIZ=${CABOT_SHOW_PEOPLE_RVIZ:-0}
      - CABOT_USE_REALSENSE=${CABOT_USE_REALSENSE:-0}
      - CABOT_REALSENSE_SERIAL
      - CABOT_CAMERA_NAME
      - CABOT_CAMERA_RGB_FPS
      - CABOT_CAMERA_DEPTH_FPS
      - CABOT_CAMERA_RESOLUTION
      - CABOT_DETECT_VERSION=${CABOT_DETECT_VERSION:-3}
      - CABOT_HEADLESS
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - CYCLONEDDS_NETWORK_INTERFACE_NAME
      - CYCLONEDDS_NETWORK_INTERFACE_AUTODETERMINE # set automatically by launch.sh
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./docker/home:/home/developer
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    stop_grace_period: 30s


  people:
    extends:
      service: people-base
    volumes:
      - ./cabot_sites:/home/developer/people_ws/src/cabot_sites
      - ./cabot-navigation/mf_localization_msgs:/home/developer/people_ws/src/mf_localization_msgs
      - ./cabot-common/cabot_common:/home/developer/people_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/people_ws/src/cabot_msgs
      - ./cabot-people/cabot_people:/home/developer/people_ws/src/cabot_people
      - ./cabot-people/track_people_py:/home/developer/people_ws/src/track_people_py
      - ./cabot-people/track_people_msgs:/home/developer/people_ws/src/track_people_msgs
      - ./cabot-people/track_people_cpp:/home/developer/people_ws/src/track_people_cpp
    command:
      - "/launch.sh"
      # - "/launch-core.sh"                 # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-K"                                # tracking
      - "-O"                                # obstacle


  people-nuc:
    extends:
      service: people-base
    build:
      context: ./docker/people
      dockerfile: Dockerfile.nuc
    volumes:
      - ./cabot-common/cabot_common:/home/developer/people_nuc_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/people_nuc_ws/src/cabot_msgs
      - ./cabot_sites:/home/developer/people_nuc_ws/src/cabot_sites
      - ./cabot-navigation/mf_localization_msgs:/home/developer/people_nuc_ws/src/mf_localization_msgs
      - ./cabot-people/cabot_people:/home/developer/people_nuc_ws/src/cabot_people
      - ./cabot-people/track_people_py:/home/developer/people_nuc_ws/src/track_people_py
      - ./cabot-people/track_people_msgs:/home/developer/people_nuc_ws/src/track_people_msgs
      - ./cabot-people/track_people_cpp:/home/developer/people_nuc_ws/src/track_people_cpp
    command:
      - "/launch.sh"
      - "-W"                                # wait roscore
      - "-K"                                # tracking
      - "-O"                                # obstacle


  people-detection:
    extends:
      service: people
    command:
      - "/launch.sh"
      # - "/launch-core.sh"   # use core dump
      - "-W"                                # wait roscore
      # - "-p"                                # people topic is simulation groundtruth
      - "-D"                                # detection
      - "-a"                                # no resetrs individually

  wifi_scan:
    build:
      context: ./cabot-drivers/wireless_scanner_ros
    environment:
      - ROS_LOG_DIR
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - ./docker/home/.ros/log:/home/developer/.ros/log
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    command: ros2 launch wireless_scanner_ros esp32.launch.xml

  ble_scan:
    build:
      context: ./cabot-drivers/wireless_scanner_ros
    environment:
      - ROS_LOG_DIR
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /sys/class/bluetooth:/sys/class/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
      - /var/lib/bluetooth:/var/lib/bluetooth
      - ./docker/home/.ros/log:/home/developer/.ros/log
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    command: ros2 launch wireless_scanner_ros dbus_ibeacon_scanner.launch.xml
