version: "2.3"

services:
  ros2:
    build:
      context: docker/ros2
      dockerfile: Dockerfile.latest
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_LOG_DIR
# CaBot
      - CABOT_GAZEBO=${CABOT_GAZEBO:-1}
      - CABOT_SITE
      - CABOT_SHOW_ROS2_RVIZ=${CABOT_SHOW_ROS2_RVIZ:-1}
      - CABOT_SHOW_ROS2_LOCAL_RVIZ
      - CABOT_RECORD_ROSBAG2=${CABOT_RECORD_ROSBAG2:-1}
      - CABOT_FOOTPRINT_RADIUS
      - CABOT_OFFSET
      - CABOT_MODEL
      - CABOT_INITX
      - CABOT_INITY
      - CABOT_INITZ
      - CABOT_INITA
      - RMW_IMPLEMENTATION
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./docker/home:/home/developer/
      # device
      - /dev:/dev
    privileged: true
    devices:
      - /dev/dri
    network_mode: host
    tty: true
    stdin_open: true
    command: ["bash"]
    stop_signal: SIGINT
