version: "2.3"

services:
  cabot:
    build:
      context: ./docker
    environment:
# display
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /tmp/.docker.xauth
      NVIDIA_DRIVER_CAPABILITIES: compute,graphics,utility,video,display
      NVIDIA_VISIBLE_DEVICES: all
# ROS
      HOSTNAME: localhost

    volumes:
# display
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /sys/class/bluetooth:/sys/class/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
# audio
      - /run/user:/run/user
# dev code
      - ./home:/home/developer
      - ./cabot:/home/developer/catkin_ws/src/cabot
      - ./cabot_description:/home/developer/catkin_ws/src/cabot_description
      - ./cabot_gazebo:/home/developer/catkin_ws/src/cabot_gazebo
      - ./cabot_msgs:/home/developer/catkin_ws/src/cabot_msgs
      - ./cabot_navigation:/home/developer/catkin_ws/src/cabot_navigation
      - ./cabot_ui:/home/developer/catkin_ws/src/cabot_ui
      - ./script:/home/developer/catkin_ws/script
      - ./exp:/home/developer/catkin_ws/exp
# required for display or device
    privileged: true
# device, bluetooth
    devices:
      - /dev/dri
# display
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
# device, bluetooth
    network_mode: host
    #command: 'launch.sh -s -r cabot2-gt1 -T cabot_site_cmu -u -z -i -B -O -H'

