# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# configuration of real robot for 3 FRAMOS on a PC configuration
# services extend from docker-compose-rs3-framos.yaml

services:
  # dev
  navigation-dev:
    extends:
      file: docker-compose-common.yaml
      service: navigation-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0
      - CABOT_TOUCH_ENABLED=${CABOT_TOUCH_ENABLED:-true}
    profiles:
      - dev

  gui-dev:
    extends:
      file: docker-compose-common.yaml
      service: gui-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0
    profiles:
      - dev

  driver-dev:
    extends:
      file: docker-compose-common.yaml
      service: driver-dev
    profiles:
      - dev

  localization-dev:
    extends:
      file: docker-compose-common.yaml
      service: localization-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_PRESSURE_AVAILABLE=1
    profiles:
      - dev

  exploration-dev:
    extends:
      file: docker-compose-common.yaml
      service: exploration-dev
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_SIM_TIME=1
    profiles:
      - dev

  exploration-prod:
    extends:
      file: docker-compose-common.yaml
      service: exploration-prod
    environment:
      - CABOT_GAZEBO=1
      - CABOT_USE_SIM_TIME=1
    profiles:
      - prod

# people service only queue and tracking
  people-track-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-track-dev
    environment:
      - CABOT_GAZEBO=0
    profiles:
      - dev

  people-rs1-framos-camera-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_1:-rs1}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - dev

  people-rs1-framos-detection-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_1:-rs1}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    profiles:
      - dev

  people-rs2-framos-camera-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_2:-rs2}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - dev

  people-rs2-framos-detection-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_2:-rs2}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    profiles:
      - dev

  people-rs3-framos-camera-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_3:-rs3}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - dev

  people-rs3-framos-detection-dev:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-dev
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_3:-rs3}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    profiles:
      - dev

  ble_scan-dev:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan-dev
    profiles:
      - dev

  # prodimg
  navigation-prod:
    extends:
      file: docker-compose-common.yaml
      service: navigation-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0
      - CABOT_TOUCH_ENABLED=${CABOT_TOUCH_ENABLED:-true}
    profiles:
      - prod

  gui-prod:
    extends:
      file: docker-compose-common.yaml
      service: gui-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_SIM_TIME=0
    profiles:
      - prod

  driver-prod:
    extends:
      file: docker-compose-common.yaml
      service: driver-prod
    profiles:
      - prod

  localization-prod:
    extends:
      file: docker-compose-common.yaml
      service: localization-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_PRESSURE_AVAILABLE=1
    profiles:
      - prod

# people service only queue and tracking
  people-track-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-track-prod
    environment:
      - CABOT_GAZEBO=0
    profiles:
      - prod

  people-rs1-framos-camera-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_1:-rs1}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - prod

  people-rs1-framos-detection-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_1:-rs1}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_1}
    profiles:
      - prod

  people-rs2-framos-camera-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_2:-rs2}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - prod

  people-rs2-framos-detection-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_2:-rs2}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_2}
    profiles:
      - prod

  people-rs3-framos-camera-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-camera-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_USE_REALSENSE=1
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_3:-rs3}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    cpuset: "11" # assume other processes don't use this cpu by isolcpus kernel option
    profiles:
      - prod

  people-rs3-framos-detection-prod:
    extends:
      file: docker-compose-common.yaml
      service: people-framos-detection-prod
    environment:
      - CABOT_GAZEBO=0
      - CABOT_CAMERA_NAME=${CABOT_CAMERA_NAME_3:-rs3}
      - CABOT_REALSENSE_SERIAL=${CABOT_REALSENSE_SERIAL_3}
    profiles:
      - prod

  ble_scan-prod:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan-prod
    profiles:
      - prod
