# Copyright (c) 2021  IBM Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

services:
  localization:
    build:
      context: ./docker/localization
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
      - OUTPUT_PREFIX
      - RUN_CARTOGRAPHER=${RUN_CARTOGRAPHER:-true}
      - USE_XSENS
      - USE_ARDUINO
      - CABOT_MODEL
      - PLAYBAG_RATE_CARTOGRAPHER
      - PLAYBAG_RATE_PC2_CONVERT
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ./docker/home:/home/developer
      - ./cabot_description2:/home/developer/loc_ws/src/cabot_description2
      - ./cabot_mf_localization:/home/developer/loc_ws/src/cabot_mf_localization
      - ./wireless_scanner_ros2:/home/developer/loc_ws/src/wireless_scanner_ros2
      - ./mf_localization:/home/developer/loc_ws/src/mf_localization
      - ./mf_localization_gazebo:/home/developer/loc_ws/src/mf_localization_gazebo
      - ./mf_localization_msgs2:/home/developer/loc_ws/src/mf_localization_msgs2
      - ./mf_localization_rviz:/home/developer/loc_ws/src/mf_localization_rviz
      - ./mf_localization_mapping:/home/developer/loc_ws/src/mf_localization_mapping
      - ./cabot_sites2:/home/developer/loc_ws/src/cabot_sites2
      - ./cabot2:/home/developer/loc_ws/src/cabot2
      - ./motor_controller:/home/developer/loc_ws/src/motor_controller
      - ./queue_msgs:/home/developer/loc_ws/src/queue_msgs
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    tty: true
    stdin_open: true
    command: /launch.sh mapping -C -X

  ros2:
    build:
      context: ./docker/ros2
    environment:
      - DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./docker/home:/home/developer
      - ./cabot_ui2:/home/developer/ros2_ws/src/cabot_ui2
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    network_mode: host
    stop_signal: SIGINT
    command: bash -c "source install/setup.bash && ros2 launch cabot_ui cabot_diagnostic.launch.py config_file:=/home/developer/ros2_ws/src/cabot_ui2/config/cabot_mapping_diagnostic.yaml"

  wifi_scan:
    extends:
      file: docker-compose-common.yaml
      service: wifi_scan

  ble_scan:
    extends:
      file: docker-compose-common.yaml
      service: ble_scan
