# Copyright (c) 2020, 2021  Carnegie Mellon University, IBM Corporation, and others
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "2.3"

services:
  navigation:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: navigation-base
    volumes:
      - ./docker/home:/home/developer/

  gazebo:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: gazebo-base
    volumes:
      - ./docker/home:/home/developer/

  gui:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: gui-base
    volumes:
      - ./docker/home:/home/developer/

  localization:
    extends:
      file: cabot-navigation/docker-compose-common.yaml
      service: localization-base
    volumes:
      - ./docker/home:/home/developer/

  driver:
    extends:
      file: cabot-drivers/docker-compose-base.yaml
      service: driver-base
    volumes:
      - ./docker/home:/home/developer/

  people:
    extends:
      file: cabot-people/docker-compose-base.yaml
      service: people-all-base
    volumes:
      - ./docker/home:/home/developer

  people-detection:
    extends:
      file: cabot-people/docker-compose-base.yaml
      service: people-detection-base
    volumes:
      - ./docker/home:/home/developer

  people-nuc:
    extends:
      file: cabot-people/docker-compose-base.yaml
      service: people-nuc-base
    volumes:
      - ./docker/home:/home/developer

  wifi_scan:
    build:
      context: ./cabot-drivers/wireless_scanner_ros
    environment:
      - ROS_LOG_DIR
    volumes:
      - /dev:/dev
      - /sys/devices:/sys/devices
      - ./docker/home/.ros/log:/home/developer/.ros/log
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    command: ros2 launch wireless_scanner_ros esp32.launch.xml

  ble_scan:
    build:
      context: ./cabot-drivers/wireless_scanner_ros
    environment:
      - ROS_LOG_DIR
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /sys/class/bluetooth:/sys/class/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
      - /var/lib/bluetooth:/var/lib/bluetooth
      - ./docker/home/.ros/log:/home/developer/.ros/log
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    network_mode: host
    stop_signal: SIGINT
    command: ros2 launch wireless_scanner_ros dbus_ibeacon_scanner.launch.xml
