# config file for hesai lidar node

# default parameters
hesai_lidar:
  ros__parameters:
    pcap_file: ""
    server_ip: "192.168.1.201"
    lidar_recv_port: 2368
    gps_port: 10110
    start_angle: 0.0
    lidar_type: "PandarXT-32"
    frame_id: "PandarXT-32"
    pcldata_type: 0
    publish_type: "both"
    timestamp_type: ""
    lidar_correction_file: "$(find-pkg-share hesai_lidar)/config/PandarXT-32.csv"
    multicast_ip: ""
    coordinate_correction_flag: False
    fixed_frame: ""
    target_frame_frame: ""