version: "2.3"

services:
  ros1:
    command:
      - "launch.sh"
      # - "-d"                                # debug
      - "-T ${CABOT_SITE:-cabot_site_cmu}"  # cabot site
      - "-r ${ROBOT:-cabot2-gt1}"           # robot type
      - "-u"                                # UI manager
      - "-z"                                # remote control
      # - "-G ${GAMEPAD:-gamepad}"            # remote control type
      - "-i"                                # not launch move_base/amcl (use ROS2 nav2
      - "-B"                                # set bridge options
      - "-O"                                # optimize visual (not launch rviz)
      - "-x ${CABOT_INITX:-0}"              # initial X
      - "-y ${CABOT_INITY:-0}"              # initial Y
      - "-Z ${CABOT_INITZ:-0}"              # initial Z
      - "-a ${CABOT_INITA:-0}"              # initial rotation
      # - "-e gt1"                            # use ble connection with name gt1
      # - "-L ja"                             # use Japanese
      # - "-X"                                # enable touch-sensor-based speed limit
      # - "-b test"                           # record bag
      - "-c"                                # use built cache                             

  ros2:
    command:
      - "/launch.sh"
      - "-T ${CABOT_SITE:-cabot_site_cmu}"  # cabot site
      - "-x ${CABOT_INITX:-0}"              # initial X
      - "-y ${CABOT_INITY:-0}"              # initial Y
      - "-Z ${CABOT_INITZ:-0}"              # initial Z
      - "-a ${CABOT_INITA:-0}"              # initial rotation
      - "-o"                                # do not show local rviz2
      # "-O"                                # do no show rviz2
      - "-c"                                # use built cache                             
