diagnostic_aggregator:
  ros__parameters:
    pub_rate: 1.0
    path: CaBot
    discard:
      type: diagnostic_aggregator/DiscardAnalyzer
      path: discard
      contains:
        - "Push Button"
        - "realsense2_camera_manager_aligned_depth_to_color: Frequency Status"
        - "cabot_serial: Pressure"
        - "cabot_serial: Temperature"
        - "cabot_serial: Touch"
        - "Rosserial Connection"
        - "cabot_serial: Serial Connection"
        - "rosserial_esp32: Serial Connection"

    hard_beacon:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: Beacon"
      contains:
        - "Beacon Scanner"
        - "Beacon Converter"
      remove_prefix:
        - "dbus_ibeacon_scanner: "
        - "ble_scan_converter: "

    hard_micon:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: IMU"
      contains:
        - "cabot_serial: IMU"
      remove_prefix:
        - "cabot_serial: "

    hard_wifi:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: WiFi"
      contains:
        - "esp32_wifi_scan_converter: "
        - "rosserial_esp32: WiFi"
      remove_prefix:
        - "esp32_wifi_scan_converter: "
        - "rosserial_esp32: "
        

    hard_velodyne:
      type: diagnostic_aggregator/GenericAnalyzer
      path: "Hard: Velodyne"
      contains:
        - "velodyne_driver_node: "
        - "velodyne_transform_node: "
      remove_prefix:
        - "velodyne_driver_node: "
        - "velodyne_transform_node: "
