name: Create Release

on:
  push:
    tags:
      - 'v*'  # Matches tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install vcstool
        run: |
          pip install vcstool

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import dependency and make release zip
        run: |
          ./setup-dependency.sh
          ./manage-pkg.sh -R -v ${{ github.ref_name }}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./cabot-*.zip

      - name: Build docker image
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.CABOT_BUILD_TOKEN}}" \
          https://api.github.com/repos/CMU-cabot/cabot-build/dispatches \
          -d '{"event_type": "build-release", "client_payload":{"ref_name": "${{ github.ref_name }}"}}'
        env:
          PAT: ${{ secrets.CABOT_BUILD_TOKEN }}
