name: Build Docker Image

on:
  push:
    branches: [ dev ]
    paths:
      - 'docker/**'
      - '!docker/home/**'
      - '!docker/*.sh'
      - '!docker/timezone/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install vcs
      run: pip3 install vcstool

    - name: Prepare thirdparty repos
      run: tools/setup-thirdparty-repos.sh

    - name: Prebuild images
      run: ./prebuild-docker.sh ros1 ros2 cuda

    - name: Build images
      shell: bash
      run: ./build-docker.sh ros1 ros2 bridge localization people people-nuc wireless

    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Upload Images
      shell: bash
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        SHORT_SHA: ${{ steps.vars.outputs.sha_short }}
      run: |
        docker login -u daisukesato80 -p "$DOCKERHUB_TOKEN"
        ./manage-docker-image.sh -a tag -i all -o cmucal -t ${GITHUB_REF_NAME}-${SHORT_SHA}
        ./manage-docker-image.sh -a tag -i all -o cmucal -t latest
        ./manage-docker-image.sh -a push -i all -o cmucal -t ${GITHUB_REF_NAME}-${SHORT_SHA}
        ./manage-docker-image.sh -a push -i all -o cmucal -t latest
