name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Matches tags like v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export release dependency
        run: ./setup-dependency.sh -r

      - name: Create zip file
        run: |
          name=$(basename $(pwd))
          cd ..
          zip -r cabot-${{ github.ref_name }}.zip ${name}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./*.zip
