name: Build Docker Image

on:
  push:
    branches: [ ros2 ]
    paths:
      - '.github/workflows/build-docker-image.yaml'
      - '**'
      - '!docker/home/**'
      - '!docker/*.sh'
      - '!docker/timezone/**'
      - '!docker/uid/**'

jobs:

  build-people:
    uses: cmu-cabot/cabot/.github/workflows/build-and-push.yaml@ros2
    with:
      prebuild-name: people
      build-name: people
      push-name: people
      tag-name: ros2-dev-latest
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-people-nuc:
    uses: cmu-cabot/cabot/.github/workflows/build-and-push.yaml@ros2
    with:
      prebuild-name: navigation
      build-name: people-nuc
      push-name: people-nuc
      tag-name: ros2-dev-latest
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-ros2:
    uses: cmu-cabot/cabot/.github/workflows/build-and-push.yaml@ros2
    with:
      prebuild-name: navigation
      build-name: ros2
      push-name: ros2
      tag-name: ros2-dev-latest
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-localization:
    uses: cmu-cabot/cabot/.github/workflows/build-and-push.yaml@ros2
    with:
      prebuild-name: navigation
      build-name: localization
      push-name: localization
      tag-name: ros2-dev-latest
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-ble-scan:
    uses: cmu-cabot/cabot/.github/workflows/build-and-push.yaml@ros2
    with:
      prebuild-name: navigation
      build-name: ble_scan
      push-name: ble_scan
      tag-name: ros2-dev-latest
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
