ARG FROM_IMAGE=cabot_people-jetson

FROM $FROM_IMAGE

ENV LANG en_US.UTF-8

WORKDIR /home/developer/people_ws

COPY --chown=$USERNAME:$USERNAME ./src ./src

SHELL ["/bin/bash", "-c"]

RUN source /opt/ros/$ROS_DISTRO/setup.bash && /launch.sh build
